.XyAWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebApppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8dc52684ee2fee2 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
